# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту kotmix@bk.ru если сборка упала
notifications:
  email:
    recipients:
      -konstantmik@yandex.ru
    on_success: never # default: change
    on_failure: always # defa,ult: always
env:
  global:
    - CODECOV_TOKEN="342c86e8-e3ce-473e-9bc2-38ab76502a34"

